#pragma once

/* 클라이언트에 존재하는 모든 클래스가 인클루드해야할 내용을 담는다. */
#include <process.h>


namespace Client
{
	enum LEVELID { LEVEL_STATIC, LEVEL_LOGO, LEVEL_LOBBY, LEVEL_ARENA, LEVEL_KONOHA, LEVEL_LOADING, LEVEL_END };

	enum OBJ_TYPE { PLAYER, MONSTER, BOSS, SKILL, TERRAIN, PROP, UI, COLMESH, EFFECT, SPAWNER, OBJ_END };

	const unsigned int		g_iWinSizeX = 1600;
	const unsigned int		g_iWinSizeY = 900;
	const float				g_fSizeRatio = 1.25f;


	enum class LAYER_TYPE
	{
		LAYER_COLMESH,
		LAYER_TERRAIN,
		LAYER_SKYBOX,
		LAYER_CAMERA,
		LAYER_BACKGROUND,
		LAYER_PLAYER,
		LAYER_MONSTER,
		LAYER_BOSS,
		LAYER_SKILL,
		LAYER_EFFECT,
		LAYER_UI,
		LAYER_END
	};

	enum class LAYER_COLLIDER
	{
		LAYER_BODY,
		LAYER_ATTACK,
		LAYER_CHILD,
		LAYER_END
	};


	enum class COLLIDER_ATTACK
	{
		MIDDLE,
		LEFT,
		RIGHT,
		SPINBLOWUP,
		SPINBLOWDOWN,
		ATTACK_END
	};

	enum LEVELSTATE { LOADING, INITREADY, INITSTART, INITEND, GAMEPLAY, STATEEND };

	enum class EVENTSTATE { EVENTSTART, READY, EVENT, EVENTEND, SETEND, TYPEEND };

	enum class EVENT
	{
		ARENASTART,
		PLAYERSTART,
		BATTLESTART,
		MADARAMETEOR,
		KONOHASTART,
		EVENTEND
	};

	enum CHANNELID {
		CHANNEL_BGM,
		CHANNEL_UI, CHANNEL_BACKGROUND, CHANNEL_3, CHANNEL_4,
		CHANNEL_5, CHANNEL_6, CHANNEL_7, CHANNEL_8, CHANNEL_9,
		CHANNEL_10, CHANNEL_11, CHANNEL_12, CHANNEL_13, CHANNEL_14,
		CHANNEL_15, CHANNEL_16, CHANNEL_17, CHANNEL_18, CHANNEL_19,
		CHANNEL_20, CHANNEL_21, CHANNEL_22, CHANNEL_23, CHANNEL_24,
		CHANNEL_25, CHANNEL_26, CHANNEL_27, CHANNEL_28, CHANNEL_29,
		CHANNEL_30,
		CHANNEL_END
	};
}

extern _float g_fVolume;
extern HWND g_hWnd;
extern HINSTANCE g_hInstance;
using namespace Client;



#define SERVER_IP		L"192.168.200.106"
#define SERVER_PORT		7777